# Usar la imagen oficial de MySQL
FROM mysql:8.0

# Configurar variables de entorno para MySQL
ENV MYSQL_DATABASE=recetagram \
    MYSQL_USER=admin \
    MYSQL_PASSWORD=root \
    MYSQL_ROOT_PASSWORD=root

# Exponer el puerto de MySQL
EXPOSE 3306
